<?php

/**
 * This is the entry point for the application.
 */

// Enable errors and warnings in the browser,
// https://tecadmin.net/enable-php-errors/
if (true) {
    ini_set("display_errors", 1);
    ini_set("display_startup_errors", 1);
    error_reporting(E_ALL);
}

use app\core\Application;
use app\controllers\SiteController;
use app\controllers\AuthController;

// Get the root path of the application
$rootPath = dirname(__DIR__);

// Load the autoloader, provided by Composer
require_once "$rootPath/vendor/autoload.php";

// Load environment variables from .env file,
// and make them available as $_ENV['name'] or $_SERVER['name'],
// where 'name' is the name of the variable.
// https://github.com/vlucas/phpdotenv
$dotenv = Dotenv\Dotenv::createImmutable($rootPath);
$dotenv->load();

// Create a $config array, which will be passed to the Application class.
// The super global $_ENV is generated by the PHP dotenv library, invoked above.
// Right now it contains only the database configuration.
$config = [
    "db" => [
        "dsn" => $_ENV["DB_DSN"],
        "user" => $_ENV["DB_USER"],
        "password" => $_ENV["DB_PASSWORD"],
    ]
];

$app = new Application($rootPath, $config);

$app->router->get("/", [SiteController::class, "home"]);
$app->router->get("/home", [SiteController::class, "home"]);

$app->router->get("/contact", [SiteController::class, "contact"]);
$app->router->post("/contact", [SiteController::class, "handleContact"]);

$app->router->get("/login", [AuthController::class, "login"]);
$app->router->post("/login", [AuthController::class, "login"]);

$app->router->get("/register", [AuthController::class, "register"]);
$app->router->post("/register", [AuthController::class, "register"]);

$app->run();
